name: Build pdf

on:
  push:
    tags:
      - '*'
env:
  GITHUB_TOKEN: ${{ github.token }}
  URL: https://raw.githubusercontent.com/DevOps-and-Cloud-based-Software/assignment3/${{ github.ref_name }}

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish Document
    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: Replace links
        run: |
          cp README.md README_WITH_LINKS.md
          sed -i -e "s#\(^\!\[[^]]\+\](\)\(images/\)#\1$URL/\2#g" README_WITH_LINKS.md
          for file in sources/*; do sed -i -e "s#($file)#($URL/$file)#g" README_WITH_LINKS.md ; done

      - name: urls-checker
        uses: urlstechie/urlchecker-action@master
        continue-on-error: true
        with:
          file_types: .md,yaml,json
          retry_count: 3
          exclude_patterns: http://IP:NODE_PORT,http://localhost,http://xxxxxxxxx.compute-1.amazonaws.com,http://IP

      - name: Publish PDF Document
        uses: shrink/actions-document-publish@v1
        id: publish-document
        with:
          sources: 'README_WITH_LINKS.md'

      - name: Get PDF name from README title
        id: get-pdf-name
        run: |
          title=$(head -1 README.md)
          echo "pdf_name=$name" >> $GITHUB_OUTPUT

      - name: Upload Document
        uses: actions/upload-artifact@v4
        id: upload-document
        with:
          name: "2-GitOps with FastAPI.pdf"
          path: ${{ steps.publish-document.outputs.pdf }}

      - name: Upload README_WITH_LINKS.md
        uses: actions/upload-artifact@v4
        id: upload-readme-file
        with:
          name: 'README_WITH_LINKS.md'
          path: README_WITH_LINKS.md